"""
报告生成服务 — 旧版模板引擎

DEPRECATED since v0.3.0:
此文件不再被 API 端点直接调用。报告生成已迁移至 JobManager + ReportGenerationSkill。
保留此文件作为迁移参考，后续版本将移除。

新生成路径：
  POST /api/v1/projects/:id/reports/generate → JobManager → ReportGenerationSkill
  POST /api/ai/report/jobs                     → JobManager → ReportGenerationSkill
"""

import json
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from backend.app.models.report import Report
from backend.app.models.analysis_result import AnalysisResult
from backend.app.models.project import Project


class ReportService:
    def __init__(self, db: Session):
        self.db = db

    def generate(self, project_id: int):
        project = self.db.query(Project).filter(Project.id == project_id).first()
        if not project:
            return None

        results = self.db.query(AnalysisResult).filter(
            AnalysisResult.project_id == project_id
        ).order_by(AnalysisResult.created_at.asc()).all()

        sections = [
            f"# {project.name} — 科研分析报告\n",
            f"## 1. 项目摘要\n",
            f"- **研究目标**: {project.research_goal}",
            f"- **暴露变量**: {project.exposure}",
            f"- **结局变量**: {project.outcome}",
            f"- **中介变量集**: {project.mediator_set or 'N/A'}",
            f"- **生成时间**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n",
        ]

        section_titles = {
            "image_segmentation": "## 2. AI 影像分割与脂肪表型提取",
            "gwas_analysis": "## 3. GWAS 分析结果",
            "opengwas_fetch": "## 4. OpenGWAS 数据获取结果",
            "mendelian_randomization": "## 5. 孟德尔随机化 (MR) 因果推断",
            "mediation_mr": "## 6. Mediation MR 中介蛋白分析",
            "risk_modeling": "## 7. Risk Modeling 风险建模",
        }

        for result in results:
            title = section_titles.get(result.result_type, f"## {result.result_type}")
            sections.append(f"\n{title}\n")
            try:
                summary = json.loads(result.summary_json)
                for k, v in summary.items():
                    sections.append(f"- **{k}**: {v}")
            except json.JSONDecodeError:
                sections.append("_No summary available_")

        sections.append(f"\n## 8. 结论\n")
        sections.append(f"This report presents the mock-first analysis of {project.exposure} → {project.outcome}.\n")
        sections.append(f"\n## 9. Mock-First 限制说明\n")
        sections.append("All analysis results in this report are generated by mock scripts for demonstration purposes. "
                         "They do not reflect real biological findings and should not be used for clinical decisions.\n")

        content = "\n".join(sections)
        report = self.db.query(Report).filter(
            Report.project_id == project_id
        ).order_by(Report.created_at.desc()).first()

        if report:
            report.content_markdown = content
            report.status = "final"
            report.updated_at = datetime.now(timezone.utc)
        else:
            report = Report(
                project_id=project_id,
                title=f"{project.name} — Analysis Report",
                content_markdown=content,
                status="final",
                created_at=datetime.now(timezone.utc),
                updated_at=datetime.now(timezone.utc),
            )
            self.db.add(report)
        self.db.commit()
        return report
